### PR TITLE
init: hard-lock script version

### PR DESCRIPTION
**Pull request by chr0n1x**
We're essentially feature complete (bare-bones deployment pipeline) so this is now needed since the majority of our work has been dealing with organiziation of data & service add-ons. Doing this will hard-lock clusters to a particular version of the scripts, which is good, and maintainers will force maintainers to  review changes and upgrade scripts manually (preferably via control-jenkins).

### CODE REVIEW

**Comment by adobejmong** [comment]
@chr0n1x if the intent is to lock it a specific sha,  shouldn't the command be something like `git reset --hard <sha>`? 

Also what if we just tag/create releases for mesos-systemd just like what we used to do in infrastructure? Will that be too much of an overhead?

Its a lot easier for me to work with clients/help others if I can just reference tag x.y.z for example. What do you think?

**Comment by adobejmong** [comment]
@chr0n1x thanks for the explanation in slack of locking it to the infrastructure version so 👍 from me

I still would love to tag releases as we did before if at all possible since its a lot easier when talking to clients and helping them

**Comment by chr0n1x** [comment]
@adobejmong @matthewdfuller this is still a thing that needs to be merged so that people who hard-lock to a version of these scripts in their bootstrap units will also have their locked versions respected by automations that rolling deploy other units. We ok with merging this?

**Comment by chr0n1x** [comment]
ping @adobe-platform/platform-core

**Comment by adobejmong** [comment]
👍

**Comment by matthewdfuller** [comment]
👍

**Pull request merged**
