### PR TITLE
v*/util-units/zk-health: update for exhibitor basic auth

### PR DESCRIPTION
**Pull request by chr0n1x**

### CODE REVIEW

**Comment by nBerg** [comment]
:+1:

**Comment by matthewdfuller** [comment]
Are you sure we want to update v2 too? If this is a critical bugfix, then I say go for it, but otherwise, this will impact all existing running clusters.

**Comment by anshupande** [comment]
I also thought that we do not update v2 now with new features. But looks like this is to fix old deployment ? Otherwise 👍

**Comment by matthewdfuller** [comment]
👍

**Pull request merged**
