### PR TITLE
Convert v2 services to use templates

### PR DESCRIPTION
**Pull request by cfortier2**

### CODE REVIEW

**Comment by chr0n1x** [comment]
can these be run with just `fleetctl submit` & `start`?

**Comment by cfortier2** [comment]
we need to append the number to it. So something like:

```
for i in {1..5};
do
  fleetctl start mesos-master@$i.service
done
```

**Comment by chr0n1x** [comment]
for each running instance or instance that it needs to run on??

**Comment by cfortier2** [comment]
the fleet command can be run from one host, but each service will need to be called n times for the number of control nodes that we want.

The full documentation is: https://coreos.com/fleet/docs/latest/launching-containers-fleet.html#run-a-high-availability-service

**Comment by chr0n1x** [comment]
ah ok. the only issue with this setup is that now the `init` script needs to be updated to understand this. While _we_ may know that we have 5 nodes in the control tier, the script does not. We need a reliable way to determine that number

**Comment by cfortier2** [comment]
we could probably pass in the control tier desired size?

**Comment by chr0n1x** [comment]
that doesn't seem...clean.

**Comment by cfortier2** [comment]
it's an option. or we could add a new parameter?

**Pull request closed without merging**
