### PR TITLE
Remove old zookeeper. Mount working directories.

### PR DESCRIPTION
**Pull request by cfortier2**
- remove old zookeeper install
- mount working directories so data persists between containers.

### CODE REVIEW

**Comment by iderdik** [comment]
:+1:

**Comment by chr0n1x** [comment]
@cfortier2 can you update `v2` as well?

**Comment by cfortier2** [comment]
ah. yes

**Comment by chr0n1x** [comment]
:+1: thanks for doing that!

**Comment by cfortier2** [comment]
no problem!

**Pull request merged**
