### PR TITLE
have capcom run in privileged mode

### PR DESCRIPTION
**Pull request by nBerg**

### CODE REVIEW

**Comment by chrishenry** [comment]
GIVE ALL TEH PRIVILEGE!!!!1!!

Actually, what's the reason we need to run in `privileged` mode?

**Comment by nBerg** [comment]
We think we may have found a way to prevent the haproxy restart throwing 503s, but it requires messing with iptable rules

**Comment by chrishenry** [comment]
ohh, I saw the other PR...so we're manipulating iptables on the CoreOS host via the container?

**Comment by nBerg** [comment]
yupp

**Comment by iderdik** [comment]
:+1:

**Comment by mannytoledo** [comment]
notpass

**Pull request merged**
