### PR TITLE
Mesos Master Quorum Configurable Based on Control Tier Size

### PR DESCRIPTION
**Pull request by matthewdfuller**
Removes hard coded "3" in favor of a quorum size calculation:

N = (Size + 1)/2

From: http://mesos.apache.org/documentation/latest/operational-guide/

This PR will allow us to use a control tier size of 3, 5, 7, etc. rather than just 5.

### CODE REVIEW

**Comment by anshupande** [comment]
👍

**Comment by chr0n1x** [comment]
👍

**Comment by iderdik** [comment]
👍

**Comment by matthewdfuller** [comment]
Merging with https://github.com/adobe-platform/infrastructure/pull/85

**Pull request merged**
